-- PROGRESSION - 1


-- 1. **Create table city**

create table city(
id number(11) Primary Key,
name VARCHAR(50) NOT NULL
);

-- 2. **Create table referee**

create table referee(
id number(11) PRIMARY key,
name VARCHAR(50) NOT NULL
);


-- 3. **Create table innings**

create table innings(
id number(11) PRIMARY KEY,
innings_number number(11) NOT NULL
);

-- 4. **Create table extra_type**

create table extra_type(
id number(11) PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

-- 5. **Create table skill**

create table skill(
id number(11) PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

-- 6. **Create table team**

create table team(
id number(11) PRIMARY KEY,
name VARCHAR(50) NOT NULL,
coach VARCHAR(50) NOT NULL,
home_city number(11) NOT NULL,
captain VARCHAR(50) NOT NULL,

FOREIGN KEY (home_city) references city(id)
);

-- 7. **Create table player**

CREATE TABLE PLAYER(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
COUNTRY VARCHAR(50) NOT NULL,
SKILL_ID NUMBER(11) NOT NULL,
TEAM_ID NUMBER(11) NOT NULL,

FOREIGN KEY (SKILL_ID) REFERENCES SKILL(ID),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID)
);

-- 8. **Create table venue**

CREATE TABLE VENUE (
ID NUMBER(11) PRIMARY KEY,
STADIUM_NAME VARCHAR(50) NOT NULL,
CITY_ID NUMBER(11) NOT NULL, 

FOREIGN KEY (CITY_ID) REFERENCES CITY(ID)

);

-- 9. **Create table event**

CREATE TABLE EVENT(

ID NUMBER(11) PRIMARY KEY,
INNINGS_ID NUMBER(11) NOT NULL,
EVENT_NO NUMBER(11) NOT NULL,
RAID_POINT NUMBER(11) NOT NULL,
DEFENDING_POINT NUMBER(11) NOT NULL,
CLOCK_IN_SECONDS NUMBER(11) NOT NULL,
TEAM_ONE_SCORE NUMBER(11) NOT NULL,
TEAM_TWO_SCORE NUMBER(11) NOT NULL,

FOREIGN KEY(INNINGS_ID) REFERENCES INNINGS(ID)

);

-- 10. **Create table extra_event**

CREATE TABLE EXTRA_EVENT(
ID NUMBER(11) PRIMARY KEY,
EVENT_ID NUMBER(11) NOT NULL,
EXTRA_TYPE_ID NUMBER(11) NOT NULL,
POINTS NUMBER(11) NOT NULL,
SCORING_TEAM_ID NUMBER(11) NOT NULL,

FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID),
FOREIGN KEY (EXTRA_TYPE_ID) REFERENCES EXTRA_TYPE(ID),
FOREIGN KEY (SCORING_TEAM_ID) REFERENCES TEAM(ID)

);

-- 11. **Create table outcome**

CREATE TABLE OUTCOME(

ID NUMBER(11) PRIMARY KEY,
STATUS VARCHAR(100) NOT NULL,
WINNER_TEAM_ID NUMBER(11) NOT NULL,
SCORE NUMBER(11),
PLAYER_OF_MATCH NUMBER(11) NOT NULL,

FOREIGN KEY (WINNER_TEAM_ID) REFERENCES TEAM(ID),
FOREIGN KEY (PLAYER_OF_MATCH) REFERENCES PLAYER(ID)
);

-- 12. **Create table game**

CREATE TABLE GAME(

ID NUMBER(11) PRIMARY KEY,
GAME_DATE DATE NOT NULL,
TEAM_ID_1 NUMBER(11) NOT NULL,
TEAM_ID_2 NUMBER(11) NOT NULL,
VENUE_ID NUMBER(11) NOT NULL,
OUTCOME_ID NUMBER(11) NOT NULL,
REFEREE_ID_1 NUMBER(11) NOT NULL,
REFEREE_ID_2 NUMBER(11) NOT NULL,
FIRST_INNINGS_ID NUMBER(11) NOT NULL,
SECOND_INNINGS_ID NUMBER(11) NOT NULL,

FOREIGN KEY (TEAM_ID_1) REFERENCES TEAM(ID),
FOREIGN KEY (TEAM_ID_2) REFERENCES TEAM(ID),
FOREIGN KEY (VENUE_ID) REFERENCES VENUE(ID),
FOREIGN KEY (OUTCOME_ID) REFERENCES OUTCOME(ID),
FOREIGN KEY (REFEREE_ID_1) REFERENCES VENUE(ID),
FOREIGN KEY (REFEREE_ID_2) REFERENCES VENUE(ID),
FOREIGN KEY (FIRST_INNINGS_ID) REFERENCES INNINGS(ID),
FOREIGN KEY (SECOND_INNINGS_ID) REFERENCES INNINGS(ID)
);

-- 13. **Drop table city**

DROP TABLE GAME;
DROP TABLE VENUE;
DROP TABLE EXTRA_EVENT;
DROP TABLE EVENT;
DROP TABLE OUTCOME;
DROP TABLE PLAYER;
DROP TABLE TEAM;

DROP TABLE CITY;

-- 14. **Drop table innings**

DROP TABLE INNINGS;


-- 15. **Drop table skill**

DROP TABLE SKILL;

-- 16. **Drop table extra_type**

DROP TABLE EXTRA_TYPE;
